name: Summarize Requirements in Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Permissions for Script
      run: chmod +x ./scripts/summarize_requirements.sh

    - name: Run Summary Script
      run: ./scripts/summarize_requirements.sh

    - name: Commit and Push Summary File
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add SUMMARY.md
        git commit -m "Update SUMMARY.md with latest requirements"
        git push
